name: CI/CD Hello

on: [ push ]

env:
  PROJECT_ID: projet-z1
  REGION: europe-west9
  ZONE: europe-west9-a
  CLUSTER: hello-cluster-z
  STATE_BUCKET: hello-terraform-zbucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Apply
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
      
    - name: Auth & Get GKE creds
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    - run: |
        gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT_ID

    - name: Configure Docker authentication for GCR
      run: |
        gcloud auth configure-docker --quiet

    - name: Build & Push Docker
      run: |
        docker build -t gcr.io/projet-z1/gke-cicd-terraform-hello:${{ github.sha }} .
        docker push gcr.io/projet-z1/gke-cicd-terraform-hello:${{ github.sha }}
    
    - name: Deploy to GKE
      run: |
        envsubst < k8s.yaml | kubectl apply -f -