name: CI/CD Hello

on: [ push ]

env:
  PROJECT_ID: projet-z1
  REGION: europe-west9
  ZONE: europe-west9-a
  CLUSTER: hello-cluster-z
  STATE_BUCKET: hello-terraform-zbucket
  REPO: hello-repo-z

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd infra
          terraform init -backend-config="bucket=${{ env.STATE_BUCKET }}" -backend-config="prefix=hello-z"
          terraform apply -auto-approve
      
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
          version: '>= 416.0.0'
          install_components: 'kubectl,gke-gcloud-auth-plugin'

      - name: Get GKE Creds
        run: |
          gcloud container clusters get-credentials \
          $CLUSTER --zone $ZONE --project projet-z1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build & Push Docker
        run: |
          IMAGE_HOST=${REGION}-docker.pkg.dev
          IMAGE_PATH=$IMAGE_HOST/${PROJECT_ID}/${REPO}/gke-cicd-terraform-hello:${GITHUB_SHA}
          kubectl set image deployment/gke-cicd-terraform-hello \
            nginx=$IMAGE_PATH
      
      - name: Deploy to GKE
        run: |
          envsubst < k8s.yaml | kubectl apply -f -